@startuml
actor User as U
participant "Get Quizzes by Search Endpoint" as GetQuizzesEndpoint
database "Quiz Database" as DB

U -> GetQuizzesEndpoint: Request to get quizzes by search
activate GetQuizzesEndpoint
GetQuizzesEndpoint -> U: Extract search parameters (searchName, tags)
U -> GetQuizzesEndpoint: Validate and process search parameters
deactivate GetQuizzesEndpoint
GetQuizzesEndpoint -> DB: Query quizzes based on search parameters
activate DB
DB-->DB : Validate search
DB --> GetQuizzesEndpoint: Quizzes data

deactivate DB
activate GetQuizzesEndpoint

alt Quizzes Found
    GetQuizzesEndpoint -> U: Respond with quizzes data
else No Quizzes Found
    GetQuizzesEndpoint -> U: Respond with no quizzes found message
end

deactivate GetQuizzesEndpoint
@enduml
