@startuml QuizzesUseCaseDiagram

left to right direction

actor User as UserActor
actor Student as StudentActor 
User <|-- Student
actor Teacher as TeacherActor
User <|-- Teacher
actor Admin as AdminActor
actor System as SystemActor

rectangle "Quizzes System" {
  usecase "Login" as UseCaseLogin
  usecase "Register" as UseCaseRegister
  usecase "Logout" as UseCaseLogout
  usecase "Forgot Password" as UseCaseForgotPassword
  usecase "Update Profile" as UseCaseUpdateProfile
  usecase "Send Report" as UseCaseSendReport

  usecase "Create Quiz" as UseCaseCreateQuiz
  usecase "Import Quiz" as UseCaseImportQuiz
  usecase "Update Quiz" as UseCaseUpdateQuiz
  usecase "Remove Quiz" as UseCaseRemoveQuiz
  usecase "Create Question" as UseCaseCreateQuestion
  usecase "Update Question" as UseCaseUpdateQuestion
  usecase "Remove Question" as UseCaseRemoveQuestion
  usecase "Add Answer" as UseCaseAddAnswer
  usecase "Update Answer" as UseCaseUpdateAnswer
  usecase "Remove Answer" as UseCaseRemoveAnswer

  usecase "create Game" as UseCaseCreatGame
  usecase "delete Game" as UseCaseDeleteGame
  usecase "Start Game" as UseCaseStartGame
  usecase "Join Game" as UseCaseJoinGame
  usecase "End Game" as UseCaseEndGame

  usecase "Create LeaderboardPlayer" as UseCaseCreateLeaderboard
  usecase "Delete LeaderboardPlayer" as UseCaseDeleteLeaderboard
  usecase "Calculation LeaderboardPlayer" as UseCaseCalculationLeaderboard
  usecase "View LeaderboardPlayer" as UseCaseViewLeaderboardPlayer

  useCase "Create ResultPlayer" as UseCaseCreateResultPlayer
  useCase "Delete ResultPlayer" as UseCaseDeleteResultPlayer
  useCase "Update ResultPlayer" as UseCaseUpdateResultPlayer
  usecase "View ResultPlayer" as UseCaseResultPlayer
  usecase "View ResultHost" as UseCaseResultHost

  usecase "View Community" as UseCaseViewCommunity
  useCase "Create Commnity" as UseCaseCreateCommunity
  useCase "Update Community" as UseCaseUpdateCommunity
  useCase "Delete Community" as UseCaseDeleteCommunity
  useCase "Delete Member Community" as UseCaseDeleteMemberCommunity
  useCase "Add Member Community" as UseCaseAddMemberCommunity
  useCase "Add Quiz Community" as UseCaseAddQuizCommunity
  useCase "Delete Quiz Community" as UseCaseDeleteQuizCommunity

  usecase "Manage Users" as UseCaseManageUsers
  usecase "Manage Quizzes" as UseCaseManageQuizzes
  usecase "Manage Questions" as UseCaseManageQuestions
  usecase "Manage Games" as UseCaseManageGames
  usecase "Manage LeaderBoards" as UseCaseManageLeaderBoards
  usecase "Manage PlayerResults" as UseCaseManagePlayerResults
  usecase "Manage Communities" as UseCaseManageCommunities
}

UserActor --> UseCaseLogin
UserActor --> UseCaseRegister
UserActor --> UseCaseLogout
UserActor --> UseCaseForgotPassword
UserActor --> UseCaseUpdateProfile
UserActor --> UseCaseSendReport
UserActor --> UseCaseJoinGame
UserActor --> UseCaseViewLeaderboard
UserActor --> UseCaseViewCommunity
UserActor --> UseCaseJoinCommunity
UserActor --> UseCaseCreateResultPlayer
UserActor --> UseCaseUpdateResultPlayer
UserActor --> UseCaseDeleteResultPlayer
UserActor --> UseCaseUpdateAnswer
UserActor --> UseCaseRemoveAnswer
UserActor --> UseCaseResultPlayer

TeacherActor --> UseCaseCreateQuiz
TeacherActor --> UseCaseImportQuiz
TeacherActor --> UseCaseUpdateQuiz
TeacherActor --> UseCaseRemoveQuiz
TeacherActor --> UseCaseCreateQuestion
TeacherActor --> UseCaseRemoveQuestion
TeacherActor --> UseCaseAddAnswer
TeacherActor --> UseCaseUpdateAnswer
TeacherActor --> UseCaseRemoveAnswer
TeacherActor --> UseCaseCreatGame
TeacherActor --> UseCaseStartGame
TeacherActor --> UseCaseDeleteGame
TeacherActor --> UseCaseEndGame
TeacherActor --> UseCaseCreateLeaderboard
TeacherActor --> UseCaseDeleteLeaderboard
TeacherActor --> UseCaseResultHost
TeacherActor --> UseCaseCreateCommunity
TeacherActor --> UseCaseUpdateCommunity
TeacherActor --> UseCaseDeleteCommunity
TeacherActor --> UseCaseAddMemberCommunity
TeacherActor --> UseCaseDeleteMemberCommunity
TeacherActor --> UseCaseAddQuizCommunity
TeacherActor --> UseCaseDeleteQuizCommunity

SystemActor --> UseCaseCalculationLeaderboard

AdminActor --> UseCaseManageUsers
AdminActor --> UseCaseManageQuizzes
AdminActor --> UseCaseManageQuestions
AdminActor --> UseCaseManageGames
AdminActor --> UseCaseManageLeaderBoards
AdminActor --> UseCaseManagePlayerResults
AdminActor --> UseCaseManageCommunities

@enduml