@startuml Search Quiz

rectangle "Search Quiz" {
    start
    :User initiates quiz search;
    :Browse available quizzes;
    while (Quizzes available?) is (yes)
    :Select quiz of interest;
    :View quiz details;
    endwhile (no)
    stop
}
@enduml
