@startuml RegisterSequence
actor User
User -> App: Request SignUp
activate App

User --> App: Provide Registration Information
User -> App: Username, Password, Email, userType, etc.

alt Registration Data Valid
    App -> Database: Check Availability
    activate Database
    App <-- Database: Data Available
    App -> Database: Create Account
    App <-- Database: Account Created
    App -> User: SignUp Successful
    User <-- App: Registered
    deactivate Database
else Registration Data Invalid
    App --> User: Invalid Data
end

deactivate App
@enduml