@startuml Take a Quiz

rectangle "Take a Quiz"  {
    start
  :User selects a quiz to take;
  :Load quiz questions;
  while (Questions remaining?) is (yes)
    :Display next question;
    :User answers the question;
    :Verify answer;
    if (Answer correct?) then (yes)
      :Award points;
    else (no)
      :No points awarded;
    endif
  endwhile (no)
  :Calculate total score;
  :Display final score;
  stop
}

@enduml
