@startuml ImportQuizSequece
actor User
User -> App: ImportQuiz
activate App

User --> App: Provide Quiz Details
User -> App: Source, Format, Options, etc.

alt Valid Details
    App -> ImportService: Import Quiz
    activate ImportService
    App <-- ImportService: Quiz Imported
    App -> User: Quiz Imported Successfully
    User <-- App: Quiz Imported
    deactivate ImportService
else Invalid Details
    App --> User: Invalid Details
end

deactivate App
@enduml