@startuml AddMemberCommunitySequence

actor User
User -> App: AddMemberCommunity
activate App

User --> App: Select Community and Member to Add
User -> App: Community Name, Member Name, Confirmation, etc.

alt Confirmation Granted
    App -> CommunityDatabase: Check Community Existence
    activate CommunityDatabase
    App <-- CommunityDatabase: Community Exists
    App -> CommunityDatabase: Check Member Existence
    App <-- CommunityDatabase: Member Exists
    App -> CommunityDatabase: Add Member to Community
    App <-- CommunityDatabase: Member Added to Community
    App -> User: Member Added Successfully
    User <-- App: Member Added
    deactivate CommunityDatabase
else Confirmation Denied
    App --> User: Addition Canceled
end

deactivate App
@enduml