@startuml
|User|
start
:1. User selects "Start a game";
|#AntiqueWhite|System|
:2. Displays a confirmation dialog to start the game.;
|User|
:3. User selects the option in the dialog (Yes or No);
|#AntiqueWhite|System|
if (4. Check Option ?) then (yes)
  :6 .Close the dialog box;
  :7 .The game begins;
  :8 .Send events to other players;
else (no)
|#AntiqueWhite|System|
  :5 .Close the dialog box;
  stop
endif
|User|
:9. User is redirected to the HostGame Screen;
|User|
stop
@enduml