@startuml PlayGameSequence

actor Player
Player -> App: PlayGame
activate App

Player --> App: Select Game, Options, etc.

alt Game Ready
    App -> GameServer: Start Game
    activate GameServer
    App <-- GameServer: Game Started
    App -> Player: Game is Ready
    Player <-- App: Game Ready
    deactivate GameServer
else Game Unavailable
    App --> Player: Game Not Available
    deactivate App
    @enduml
end