@startuml Report Content

rectangle "Report Content"{
    start
  :User selects content to report;
  :Provide reason for report;
  :Submit report;
  if (Report submitted successfully?) then (yes)
    :Report under review;
    :Moderators evaluate the report;
    if (Content violates policies?) then (yes)
      :Take necessary action;
    else (no)
      :No action taken;
    endif
  else (no)
    :Report submission failed;
    stop
  endif
  stop
}


@enduml
