@startuml
|User|
start
:1. User select "View LeaderBoard";
|#AntiqueWhite|System|
:2. Displays a list of user rankings.;
|User|
:3. User select a specific user;
|#AntiqueWhite|System|
:4. Displays user's personal information;
|User|
:5. View details about user information;

stop
@enduml