@startuml
actor User as U
participant "Create Quiz Endpoint" as CreateQuizEndpoint
database "Quiz Database" as QuizDB
database "Question Database" as QuestionDB
control "Validation Module" as ValidationModule

U -> CreateQuizEndpoint: Request to create quiz
activate CreateQuizEndpoint
CreateQuizEndpoint -> ValidationModule: Validate and extract quiz data
activate ValidationModule
ValidationModule --> ValidationModule: Validate quiz data
ValidationModule --> CreateQuizEndpoint: Validation result
deactivate ValidationModule
U -> CreateQuizEndpoint: Send request with validated quiz data

CreateQuizEndpoint -> QuestionDB: Create and save questions
activate QuestionDB
QuestionDB --> QuestionDB: Validate save question
QuestionDB --> CreateQuizEndpoint: Saved question data
deactivate QuestionDB
CreateQuizEndpoint -> QuizDB: Create and save quiz
activate QuizDB
QuizDB --> QuizDB: Validate save data
QuizDB --> CreateQuizEndpoint: Saved quiz data
deactivate QuizDB
CreateQuizEndpoint -> U: Respond with created quiz data
deactivate CreateQuizEndpoint
@enduml
