@startuml CreateQuizSequece
actor User
User -> App: CreateQuiz
activate App

User --> App: Provide Quiz Details
User -> App: Title, Questions, pointQuiz , Options, etc.

alt Valid Details
    App -> Database: Save Quiz
    activate Database
    App <-- Database: Quiz Saved
    App -> User: Quiz Created Successfully
    User <-- App: Quiz Created
    deactivate Database
else Invalid Details
    App --> User: Invalid Details
end

deactivate App
@enduml